---
title: "Readme"
author: "Jose Carlos"
date: "24/7/2019"
output: rmarkdown::github_document
---
<!-- README.md is generated from README.Rmd. Please edit that file -->
##Data Mining Use
Usual Functions for Data Mining

#Functions to join Data frames & vectors without errors

```{r example, echo=FALSE}
library(data.table)
suppressPackageStartupMessages(library(tidyverse))
dft<-function(df){
  if(class(df)%in% "tibble"){Tib<-TRUE}
  else{Tib<-FALSE}
  df_1<-as.data.frame(t(df))
  names(df_1)<-row.names(df)
  if(Tib){return(dplyr::as_tibble(df_1))}
  else{return(df_1)}
}
CBIND<-function(df1,df2){
  is_df<-purrr::map_lgl(list(df1,df2),is.data.frame)
  if(any(is_df)){#hay al menos uno que no es df
    df1<-tibble::as_tibble(df1)
    df2<-tibble::as_tibble(df2)
  }
  nd1<-nrow(df1);nd2<-nrow(df2)
  if(nd1==nd2){
    return(cbind(df1,df2))
  }
  else{
    mxm<-c(nd1,nd2)!=max(c(nd1,nd2))
    dmx<-list(df1,df2)[mxm][[1]]
    dmn<-list(df1,df2)[!mxm][[1]]
    
    df_rw<-c(nd1,nd2)[mxm]-c(nd1,nd2)[!mxm]
    dmx<-rbind(dmx,tibble::as_tibble(matrix(NA,-df_rw,ncol(dmx),
                               dimnames = list(rep(NA,-df_rw),names(dmx)))))
    #a partir de aquí ambos df's tienen las mismas columnas
  if(is_df[1]){
    return(cbind(dmn,dmx))
  }else{
    return(cbind(dmx,dmn))
  }
  }
}
RBIND<-function(df1,df2){
  nd1<-ncol(df1);nd2<-ncol(df2)
  if(nd1==nd2 &&
     all(names(df1)==names(df2))){
    return(rbind(df1,df2))
  }else{
    mxm<-c(nd1,nd2)!=max(c(nd1,nd2))
    if(all(mxm==F)){mxm<-c(TRUE,FALSE)}
    dmx<-list(df1,df2)[mxm][[1]]
    dmn<-list(df1,df2)[!mxm][[1]]
    min_ex<-names(dmn)[!names(dmn) %in% names(dmx)]
    max_ex<-names(dmx)[!names(dmx) %in% names(dmn)]
    if(length(min_ex)+length(max_ex)==0){
      dmn<-cbind(dmn,tibble::as_tibble(matrix(NA,nrow(dmn),c(nd1,nd2)[mxm]-c(nd1,nd2)[!mxm],
                                      dimnames = list(1:nrow(dmn),max_ex))))
    }else{#Csos en donde ambos df tengan otras columnas
      dmn<-cbind(dmn,tibble::as_tibble(matrix(NA,nrow(dmn),length(max_ex),
                                      dimnames = list(1:nrow(dmn),max_ex))))
      
      dmx<-cbind(dmx,tibble::as_tibble(matrix(NA,nrow(dmx),length(min_ex),
                                      dimnames = list(1:nrow(dmx),min_ex))))
      
    }
    
    if(nd1<nd2 | mxm[1])#Si el primer argumento es mxm o si tiene menos columnas
      return(rbind(dmx,dmn))
    else
      return(rbind(dmn,dmx))
  }
}
drop.df<-function(df){
  df[,purrr::map_lgl(df,~length(unique(.x))>1)]
}


data(iris)
```

Data to join

```{r irisss, echo=TRUE}
df2<-iris[,5]
head(df2)
```

```{r iris, echo=TRUE}
df1<-rbind(iris,iris)
data.table(head(df1))
```
We will join a data frame of dim (300,5) with a vector of (150,1) 

```{r cbindtable, echo=TRUE}
dfc<-suppressWarnings(CBIND(df1,df2))
head(dfc)
```


There is a RBIND version as well
```{r exmple}
data(iris)
d_1<-iris[1,]
d_1$Species<-as.character(d_1$Species)
d_1[1,5]<-"Rse"
d_1[["Nueva"]]<-c("U")
head(d_1)
```
```{r eoof}
ir<-iris
ir$W<-"rr"
head(ir)
```
```{r eoofw}
head(RBIND(d_1,ir))
```

#Functions to clean Data frames

```{r exaewemple}
iris[["A"]]<-0
head(iris)
```

Cleaning process, dropping unused columns

```{r exampaale}
head(drop.df(iris))
```

#Functions to modify Data frames
```{r exa32mple}
dft(iris)[,1:5]
```


